/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSalairesRouteImport } from './routes/_authenticated/salaires'
import { Route as AuthenticatedPresencesRouteImport } from './routes/_authenticated/presences'
import { Route as AuthenticatedPaiementsRouteImport } from './routes/_authenticated/paiements'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedEnseignantsRouteImport } from './routes/_authenticated/enseignants'
import { Route as AuthenticatedEmploiDuTempsRouteImport } from './routes/_authenticated/emploi-du-temps'
import { Route as AuthenticatedElevesRouteImport } from './routes/_authenticated/eleves'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedComptabiliteRouteImport } from './routes/_authenticated/comptabilite'
import { Route as AuthenticatedClassesRouteImport } from './routes/_authenticated/classes'
import { Route as AuthenticatedBulletinsRouteImport } from './routes/_authenticated/bulletins'
import { Route as AuthenticatedAnnoncesRouteImport } from './routes/_authenticated/annonces'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSalairesRoute = AuthenticatedSalairesRouteImport.update({
  id: '/salaires',
  path: '/salaires',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPresencesRoute = AuthenticatedPresencesRouteImport.update({
  id: '/presences',
  path: '/presences',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaiementsRoute = AuthenticatedPaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnseignantsRoute =
  AuthenticatedEnseignantsRouteImport.update({
    id: '/enseignants',
    path: '/enseignants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmploiDuTempsRoute =
  AuthenticatedEmploiDuTempsRouteImport.update({
    id: '/emploi-du-temps',
    path: '/emploi-du-temps',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedElevesRoute = AuthenticatedElevesRouteImport.update({
  id: '/eleves',
  path: '/eleves',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComptabiliteRoute =
  AuthenticatedComptabiliteRouteImport.update({
    id: '/comptabilite',
    path: '/comptabilite',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassesRoute = AuthenticatedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBulletinsRoute = AuthenticatedBulletinsRouteImport.update({
  id: '/bulletins',
  path: '/bulletins',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnnoncesRoute = AuthenticatedAnnoncesRouteImport.update({
  id: '/annonces',
  path: '/annonces',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/annonces': typeof AuthenticatedAnnoncesRoute
  '/bulletins': typeof AuthenticatedBulletinsRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/comptabilite': typeof AuthenticatedComptabiliteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/eleves': typeof AuthenticatedElevesRoute
  '/emploi-du-temps': typeof AuthenticatedEmploiDuTempsRoute
  '/enseignants': typeof AuthenticatedEnseignantsRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/paiements': typeof AuthenticatedPaiementsRoute
  '/presences': typeof AuthenticatedPresencesRoute
  '/salaires': typeof AuthenticatedSalairesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/annonces': typeof AuthenticatedAnnoncesRoute
  '/bulletins': typeof AuthenticatedBulletinsRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/comptabilite': typeof AuthenticatedComptabiliteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/eleves': typeof AuthenticatedElevesRoute
  '/emploi-du-temps': typeof AuthenticatedEmploiDuTempsRoute
  '/enseignants': typeof AuthenticatedEnseignantsRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/paiements': typeof AuthenticatedPaiementsRoute
  '/presences': typeof AuthenticatedPresencesRoute
  '/salaires': typeof AuthenticatedSalairesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/annonces': typeof AuthenticatedAnnoncesRoute
  '/_authenticated/bulletins': typeof AuthenticatedBulletinsRoute
  '/_authenticated/classes': typeof AuthenticatedClassesRoute
  '/_authenticated/comptabilite': typeof AuthenticatedComptabiliteRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/eleves': typeof AuthenticatedElevesRoute
  '/_authenticated/emploi-du-temps': typeof AuthenticatedEmploiDuTempsRoute
  '/_authenticated/enseignants': typeof AuthenticatedEnseignantsRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/paiements': typeof AuthenticatedPaiementsRoute
  '/_authenticated/presences': typeof AuthenticatedPresencesRoute
  '/_authenticated/salaires': typeof AuthenticatedSalairesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/annonces'
    | '/bulletins'
    | '/classes'
    | '/comptabilite'
    | '/dashboard'
    | '/eleves'
    | '/emploi-du-temps'
    | '/enseignants'
    | '/notes'
    | '/paiements'
    | '/presences'
    | '/salaires'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/annonces'
    | '/bulletins'
    | '/classes'
    | '/comptabilite'
    | '/dashboard'
    | '/eleves'
    | '/emploi-du-temps'
    | '/enseignants'
    | '/notes'
    | '/paiements'
    | '/presences'
    | '/salaires'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/annonces'
    | '/_authenticated/bulletins'
    | '/_authenticated/classes'
    | '/_authenticated/comptabilite'
    | '/_authenticated/dashboard'
    | '/_authenticated/eleves'
    | '/_authenticated/emploi-du-temps'
    | '/_authenticated/enseignants'
    | '/_authenticated/notes'
    | '/_authenticated/paiements'
    | '/_authenticated/presences'
    | '/_authenticated/salaires'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/salaires': {
      id: '/_authenticated/salaires'
      path: '/salaires'
      fullPath: '/salaires'
      preLoaderRoute: typeof AuthenticatedSalairesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/presences': {
      id: '/_authenticated/presences'
      path: '/presences'
      fullPath: '/presences'
      preLoaderRoute: typeof AuthenticatedPresencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/paiements': {
      id: '/_authenticated/paiements'
      path: '/paiements'
      fullPath: '/paiements'
      preLoaderRoute: typeof AuthenticatedPaiementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enseignants': {
      id: '/_authenticated/enseignants'
      path: '/enseignants'
      fullPath: '/enseignants'
      preLoaderRoute: typeof AuthenticatedEnseignantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emploi-du-temps': {
      id: '/_authenticated/emploi-du-temps'
      path: '/emploi-du-temps'
      fullPath: '/emploi-du-temps'
      preLoaderRoute: typeof AuthenticatedEmploiDuTempsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eleves': {
      id: '/_authenticated/eleves'
      path: '/eleves'
      fullPath: '/eleves'
      preLoaderRoute: typeof AuthenticatedElevesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comptabilite': {
      id: '/_authenticated/comptabilite'
      path: '/comptabilite'
      fullPath: '/comptabilite'
      preLoaderRoute: typeof AuthenticatedComptabiliteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes': {
      id: '/_authenticated/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bulletins': {
      id: '/_authenticated/bulletins'
      path: '/bulletins'
      fullPath: '/bulletins'
      preLoaderRoute: typeof AuthenticatedBulletinsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/annonces': {
      id: '/_authenticated/annonces'
      path: '/annonces'
      fullPath: '/annonces'
      preLoaderRoute: typeof AuthenticatedAnnoncesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnnoncesRoute: typeof AuthenticatedAnnoncesRoute
  AuthenticatedBulletinsRoute: typeof AuthenticatedBulletinsRoute
  AuthenticatedClassesRoute: typeof AuthenticatedClassesRoute
  AuthenticatedComptabiliteRoute: typeof AuthenticatedComptabiliteRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedElevesRoute: typeof AuthenticatedElevesRoute
  AuthenticatedEmploiDuTempsRoute: typeof AuthenticatedEmploiDuTempsRoute
  AuthenticatedEnseignantsRoute: typeof AuthenticatedEnseignantsRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedPaiementsRoute: typeof AuthenticatedPaiementsRoute
  AuthenticatedPresencesRoute: typeof AuthenticatedPresencesRoute
  AuthenticatedSalairesRoute: typeof AuthenticatedSalairesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnnoncesRoute: AuthenticatedAnnoncesRoute,
  AuthenticatedBulletinsRoute: AuthenticatedBulletinsRoute,
  AuthenticatedClassesRoute: AuthenticatedClassesRoute,
  AuthenticatedComptabiliteRoute: AuthenticatedComptabiliteRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedElevesRoute: AuthenticatedElevesRoute,
  AuthenticatedEmploiDuTempsRoute: AuthenticatedEmploiDuTempsRoute,
  AuthenticatedEnseignantsRoute: AuthenticatedEnseignantsRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedPaiementsRoute: AuthenticatedPaiementsRoute,
  AuthenticatedPresencesRoute: AuthenticatedPresencesRoute,
  AuthenticatedSalairesRoute: AuthenticatedSalairesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
