/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSouscriptionRouteImport } from './routes/_authenticated/souscription'
import { Route as AuthenticatedSauvegardeRouteImport } from './routes/_authenticated/sauvegarde'
import { Route as AuthenticatedSalairesRouteImport } from './routes/_authenticated/salaires'
import { Route as AuthenticatedRapportsRouteImport } from './routes/_authenticated/rapports'
import { Route as AuthenticatedPresencesRouteImport } from './routes/_authenticated/presences'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedParametresRouteImport } from './routes/_authenticated/parametres'
import { Route as AuthenticatedPaiementsRouteImport } from './routes/_authenticated/paiements'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedMessagerieRouteImport } from './routes/_authenticated/messagerie'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedExamensRouteImport } from './routes/_authenticated/examens'
import { Route as AuthenticatedEnseignantsRouteImport } from './routes/_authenticated/enseignants'
import { Route as AuthenticatedEmploiDuTempsRouteImport } from './routes/_authenticated/emploi-du-temps'
import { Route as AuthenticatedElevesRouteImport } from './routes/_authenticated/eleves'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedComptabiliteRouteImport } from './routes/_authenticated/comptabilite'
import { Route as AuthenticatedClassesRouteImport } from './routes/_authenticated/classes'
import { Route as AuthenticatedBulletinsRouteImport } from './routes/_authenticated/bulletins'
import { Route as AuthenticatedBibliothequeRouteImport } from './routes/_authenticated/bibliotheque'
import { Route as AuthenticatedAnnoncesRouteImport } from './routes/_authenticated/annonces'
import { Route as AuthenticatedAffectationsRouteImport } from './routes/_authenticated/affectations'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSouscriptionRoute =
  AuthenticatedSouscriptionRouteImport.update({
    id: '/souscription',
    path: '/souscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSauvegardeRoute = AuthenticatedSauvegardeRouteImport.update({
  id: '/sauvegarde',
  path: '/sauvegarde',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalairesRoute = AuthenticatedSalairesRouteImport.update({
  id: '/salaires',
  path: '/salaires',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRapportsRoute = AuthenticatedRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPresencesRoute = AuthenticatedPresencesRouteImport.update({
  id: '/presences',
  path: '/presences',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParametresRoute = AuthenticatedParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaiementsRoute = AuthenticatedPaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagerieRoute = AuthenticatedMessagerieRouteImport.update({
  id: '/messagerie',
  path: '/messagerie',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamensRoute = AuthenticatedExamensRouteImport.update({
  id: '/examens',
  path: '/examens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnseignantsRoute =
  AuthenticatedEnseignantsRouteImport.update({
    id: '/enseignants',
    path: '/enseignants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmploiDuTempsRoute =
  AuthenticatedEmploiDuTempsRouteImport.update({
    id: '/emploi-du-temps',
    path: '/emploi-du-temps',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedElevesRoute = AuthenticatedElevesRouteImport.update({
  id: '/eleves',
  path: '/eleves',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComptabiliteRoute =
  AuthenticatedComptabiliteRouteImport.update({
    id: '/comptabilite',
    path: '/comptabilite',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassesRoute = AuthenticatedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBulletinsRoute = AuthenticatedBulletinsRouteImport.update({
  id: '/bulletins',
  path: '/bulletins',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBibliothequeRoute =
  AuthenticatedBibliothequeRouteImport.update({
    id: '/bibliotheque',
    path: '/bibliotheque',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnnoncesRoute = AuthenticatedAnnoncesRouteImport.update({
  id: '/annonces',
  path: '/annonces',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAffectationsRoute =
  AuthenticatedAffectationsRouteImport.update({
    id: '/affectations',
    path: '/affectations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/affectations': typeof AuthenticatedAffectationsRoute
  '/annonces': typeof AuthenticatedAnnoncesRoute
  '/bibliotheque': typeof AuthenticatedBibliothequeRoute
  '/bulletins': typeof AuthenticatedBulletinsRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/comptabilite': typeof AuthenticatedComptabiliteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/eleves': typeof AuthenticatedElevesRoute
  '/emploi-du-temps': typeof AuthenticatedEmploiDuTempsRoute
  '/enseignants': typeof AuthenticatedEnseignantsRoute
  '/examens': typeof AuthenticatedExamensRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/messagerie': typeof AuthenticatedMessagerieRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/paiements': typeof AuthenticatedPaiementsRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/presences': typeof AuthenticatedPresencesRoute
  '/rapports': typeof AuthenticatedRapportsRoute
  '/salaires': typeof AuthenticatedSalairesRoute
  '/sauvegarde': typeof AuthenticatedSauvegardeRoute
  '/souscription': typeof AuthenticatedSouscriptionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/affectations': typeof AuthenticatedAffectationsRoute
  '/annonces': typeof AuthenticatedAnnoncesRoute
  '/bibliotheque': typeof AuthenticatedBibliothequeRoute
  '/bulletins': typeof AuthenticatedBulletinsRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/comptabilite': typeof AuthenticatedComptabiliteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/eleves': typeof AuthenticatedElevesRoute
  '/emploi-du-temps': typeof AuthenticatedEmploiDuTempsRoute
  '/enseignants': typeof AuthenticatedEnseignantsRoute
  '/examens': typeof AuthenticatedExamensRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/messagerie': typeof AuthenticatedMessagerieRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/paiements': typeof AuthenticatedPaiementsRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/presences': typeof AuthenticatedPresencesRoute
  '/rapports': typeof AuthenticatedRapportsRoute
  '/salaires': typeof AuthenticatedSalairesRoute
  '/sauvegarde': typeof AuthenticatedSauvegardeRoute
  '/souscription': typeof AuthenticatedSouscriptionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/affectations': typeof AuthenticatedAffectationsRoute
  '/_authenticated/annonces': typeof AuthenticatedAnnoncesRoute
  '/_authenticated/bibliotheque': typeof AuthenticatedBibliothequeRoute
  '/_authenticated/bulletins': typeof AuthenticatedBulletinsRoute
  '/_authenticated/classes': typeof AuthenticatedClassesRoute
  '/_authenticated/comptabilite': typeof AuthenticatedComptabiliteRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/eleves': typeof AuthenticatedElevesRoute
  '/_authenticated/emploi-du-temps': typeof AuthenticatedEmploiDuTempsRoute
  '/_authenticated/enseignants': typeof AuthenticatedEnseignantsRoute
  '/_authenticated/examens': typeof AuthenticatedExamensRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/messagerie': typeof AuthenticatedMessagerieRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/paiements': typeof AuthenticatedPaiementsRoute
  '/_authenticated/parametres': typeof AuthenticatedParametresRoute
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/presences': typeof AuthenticatedPresencesRoute
  '/_authenticated/rapports': typeof AuthenticatedRapportsRoute
  '/_authenticated/salaires': typeof AuthenticatedSalairesRoute
  '/_authenticated/sauvegarde': typeof AuthenticatedSauvegardeRoute
  '/_authenticated/souscription': typeof AuthenticatedSouscriptionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/affectations'
    | '/annonces'
    | '/bibliotheque'
    | '/bulletins'
    | '/classes'
    | '/comptabilite'
    | '/dashboard'
    | '/eleves'
    | '/emploi-du-temps'
    | '/enseignants'
    | '/examens'
    | '/journal'
    | '/messagerie'
    | '/notes'
    | '/paiements'
    | '/parametres'
    | '/plans'
    | '/presences'
    | '/rapports'
    | '/salaires'
    | '/sauvegarde'
    | '/souscription'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/affectations'
    | '/annonces'
    | '/bibliotheque'
    | '/bulletins'
    | '/classes'
    | '/comptabilite'
    | '/dashboard'
    | '/eleves'
    | '/emploi-du-temps'
    | '/enseignants'
    | '/examens'
    | '/journal'
    | '/messagerie'
    | '/notes'
    | '/paiements'
    | '/parametres'
    | '/plans'
    | '/presences'
    | '/rapports'
    | '/salaires'
    | '/sauvegarde'
    | '/souscription'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/affectations'
    | '/_authenticated/annonces'
    | '/_authenticated/bibliotheque'
    | '/_authenticated/bulletins'
    | '/_authenticated/classes'
    | '/_authenticated/comptabilite'
    | '/_authenticated/dashboard'
    | '/_authenticated/eleves'
    | '/_authenticated/emploi-du-temps'
    | '/_authenticated/enseignants'
    | '/_authenticated/examens'
    | '/_authenticated/journal'
    | '/_authenticated/messagerie'
    | '/_authenticated/notes'
    | '/_authenticated/paiements'
    | '/_authenticated/parametres'
    | '/_authenticated/plans'
    | '/_authenticated/presences'
    | '/_authenticated/rapports'
    | '/_authenticated/salaires'
    | '/_authenticated/sauvegarde'
    | '/_authenticated/souscription'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/souscription': {
      id: '/_authenticated/souscription'
      path: '/souscription'
      fullPath: '/souscription'
      preLoaderRoute: typeof AuthenticatedSouscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sauvegarde': {
      id: '/_authenticated/sauvegarde'
      path: '/sauvegarde'
      fullPath: '/sauvegarde'
      preLoaderRoute: typeof AuthenticatedSauvegardeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salaires': {
      id: '/_authenticated/salaires'
      path: '/salaires'
      fullPath: '/salaires'
      preLoaderRoute: typeof AuthenticatedSalairesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rapports': {
      id: '/_authenticated/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof AuthenticatedRapportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/presences': {
      id: '/_authenticated/presences'
      path: '/presences'
      fullPath: '/presences'
      preLoaderRoute: typeof AuthenticatedPresencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametres': {
      id: '/_authenticated/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthenticatedParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/paiements': {
      id: '/_authenticated/paiements'
      path: '/paiements'
      fullPath: '/paiements'
      preLoaderRoute: typeof AuthenticatedPaiementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messagerie': {
      id: '/_authenticated/messagerie'
      path: '/messagerie'
      fullPath: '/messagerie'
      preLoaderRoute: typeof AuthenticatedMessagerieRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/examens': {
      id: '/_authenticated/examens'
      path: '/examens'
      fullPath: '/examens'
      preLoaderRoute: typeof AuthenticatedExamensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enseignants': {
      id: '/_authenticated/enseignants'
      path: '/enseignants'
      fullPath: '/enseignants'
      preLoaderRoute: typeof AuthenticatedEnseignantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emploi-du-temps': {
      id: '/_authenticated/emploi-du-temps'
      path: '/emploi-du-temps'
      fullPath: '/emploi-du-temps'
      preLoaderRoute: typeof AuthenticatedEmploiDuTempsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eleves': {
      id: '/_authenticated/eleves'
      path: '/eleves'
      fullPath: '/eleves'
      preLoaderRoute: typeof AuthenticatedElevesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comptabilite': {
      id: '/_authenticated/comptabilite'
      path: '/comptabilite'
      fullPath: '/comptabilite'
      preLoaderRoute: typeof AuthenticatedComptabiliteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes': {
      id: '/_authenticated/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bulletins': {
      id: '/_authenticated/bulletins'
      path: '/bulletins'
      fullPath: '/bulletins'
      preLoaderRoute: typeof AuthenticatedBulletinsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bibliotheque': {
      id: '/_authenticated/bibliotheque'
      path: '/bibliotheque'
      fullPath: '/bibliotheque'
      preLoaderRoute: typeof AuthenticatedBibliothequeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/annonces': {
      id: '/_authenticated/annonces'
      path: '/annonces'
      fullPath: '/annonces'
      preLoaderRoute: typeof AuthenticatedAnnoncesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/affectations': {
      id: '/_authenticated/affectations'
      path: '/affectations'
      fullPath: '/affectations'
      preLoaderRoute: typeof AuthenticatedAffectationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAffectationsRoute: typeof AuthenticatedAffectationsRoute
  AuthenticatedAnnoncesRoute: typeof AuthenticatedAnnoncesRoute
  AuthenticatedBibliothequeRoute: typeof AuthenticatedBibliothequeRoute
  AuthenticatedBulletinsRoute: typeof AuthenticatedBulletinsRoute
  AuthenticatedClassesRoute: typeof AuthenticatedClassesRoute
  AuthenticatedComptabiliteRoute: typeof AuthenticatedComptabiliteRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedElevesRoute: typeof AuthenticatedElevesRoute
  AuthenticatedEmploiDuTempsRoute: typeof AuthenticatedEmploiDuTempsRoute
  AuthenticatedEnseignantsRoute: typeof AuthenticatedEnseignantsRoute
  AuthenticatedExamensRoute: typeof AuthenticatedExamensRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedMessagerieRoute: typeof AuthenticatedMessagerieRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedPaiementsRoute: typeof AuthenticatedPaiementsRoute
  AuthenticatedParametresRoute: typeof AuthenticatedParametresRoute
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedPresencesRoute: typeof AuthenticatedPresencesRoute
  AuthenticatedRapportsRoute: typeof AuthenticatedRapportsRoute
  AuthenticatedSalairesRoute: typeof AuthenticatedSalairesRoute
  AuthenticatedSauvegardeRoute: typeof AuthenticatedSauvegardeRoute
  AuthenticatedSouscriptionRoute: typeof AuthenticatedSouscriptionRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAffectationsRoute: AuthenticatedAffectationsRoute,
  AuthenticatedAnnoncesRoute: AuthenticatedAnnoncesRoute,
  AuthenticatedBibliothequeRoute: AuthenticatedBibliothequeRoute,
  AuthenticatedBulletinsRoute: AuthenticatedBulletinsRoute,
  AuthenticatedClassesRoute: AuthenticatedClassesRoute,
  AuthenticatedComptabiliteRoute: AuthenticatedComptabiliteRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedElevesRoute: AuthenticatedElevesRoute,
  AuthenticatedEmploiDuTempsRoute: AuthenticatedEmploiDuTempsRoute,
  AuthenticatedEnseignantsRoute: AuthenticatedEnseignantsRoute,
  AuthenticatedExamensRoute: AuthenticatedExamensRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedMessagerieRoute: AuthenticatedMessagerieRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedPaiementsRoute: AuthenticatedPaiementsRoute,
  AuthenticatedParametresRoute: AuthenticatedParametresRoute,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedPresencesRoute: AuthenticatedPresencesRoute,
  AuthenticatedRapportsRoute: AuthenticatedRapportsRoute,
  AuthenticatedSalairesRoute: AuthenticatedSalairesRoute,
  AuthenticatedSauvegardeRoute: AuthenticatedSauvegardeRoute,
  AuthenticatedSouscriptionRoute: AuthenticatedSouscriptionRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
